version: '3'
services:
  pg_db:
    container_name: restful_server
    image: postgres:10
    restart: always
    volumes:
      - postgres-data:/var/lib/postgres/restful/data
    env_file:
      - .env
    ports:
      - '5432:5432'
volumes:
  postgres-data:
